FROM python:3.10-slim

# Define an argument with a default value
ARG LANGURU_VERSION=

# Install a package with the version if specified, otherwise install the latest
RUN if [ -z "$LANGURU_VERSION" ] ; then pip install languru[all] ; else pip install languru[all]==$LANGURU_VERSION ; fi

# Set the working directory
WORKDIR /app

# Expose the port
EXPOSE 80

ENTRYPOINT ["languru"]
CMD ["version"]
